repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.5.9
  hooks:
    - id: nbqa-black
      additional_dependencies: [black==20.8b1]
      args: [--nbqa-mutate]
      exclude: ^201-vision-monocular-depth-estimation/
    - id: nbqa-pyupgrade
      additional_dependencies: [pyupgrade==2.10.0]
      args: [--nbqa-mutate, --py36-plus]
    - id: nbqa-flake8
      additional_dependencies: [flake8==3.9.0]
      args: [--nbqa-mutate]
- repo: https://github.com/kynan/nbstripout
  rev: 0.3.9
  hooks:
    - id: nbstripout

