name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --quiet --index-url https://test.pypi.org/simple --extra-index-url https://pypi.org/simple openvino-dev
        pip install matplotlib youtube_dl Pillow nbdime jupyter
    - name: Analysing the code with nbdime
      run: |
        py.test --nbdime `ls -R|grep .ipynb$|xargs`
