name: Pylint

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
        python: [3.6, 3.7]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --index-url https://test.pypi.org/simple --extra-index-url https://pypi.org/simple openvino-dev
        python -m pip install matplotlib youtube_dl Pillow nbval jupyterlab 
        python -m ipykernel install --user --name openvino_env
    - name: Analysing with nbval
      run: |
        python -m pytest --nbval superresolution/superresolution.ipynb onnx_inference_convert/pytorch_onnx_openvino.ipynb
