name: nbval

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest, windows-latest]
        python: [3.6, 3.7]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==20.1.1
        python -m pip install wheel
        python -m pip install -r requirements-dev.txt
        python -m ipykernel install --user --name openvino_env    
    - name: Analysing with nbval
      run: |
        python -m pytest --nbval superresolution/superresolution.ipynb 201-vision-monocular-depth-estimation/201-vision-monocular-depth-estimation.ipynb 201-vision-monocular-depth-estimation/201-vision-monocular-depth-estimation-image.ipynb

